---
title: "GAM model"
author: "Wanda De Keersmaecker"
date: "3/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## User inputs

```{r inputs}
# path to folder with data
ifolder <- '/home/wanda/Documents/data/upscaleRecovery/test/testdata/'#'./inst/testdata/'
# path to folder where outputs should be stored
ofolder <- '/home/wanda/Documents/data/upscaleRecovery/test/testdata/'#'./inst/testdata/'
# name of data files

```

## Load data

```{r cars}

load(file.path(ifolder, 'total_val.Rdata'))

```



```{r lin_mod_r80p}
total_val$ecoReg <-as.factor(total_val$ecoReg)

library(arm)
library(spdep)
# total_val <- total_val[complete.cases(total_val),]

# Select the most optimal tree cover range
lm_R80PTC1 <- lm(R80P ~ TCmean500, data = total_val)#
lm_R80PTC2 <- lm(R80P ~ TCmean1000, data = total_val)
lm_R80PTC3 <- lm(R80P ~ TCmean5000, data = total_val)
AIC(lm_R80PTC1, lm_R80PTC2, lm_R80PTC3)

# Select the most optimal soil depth
# lm_R80PN1 <- lm(R80P ~ Nitro_000_005, data = total_val)
# lm_R80PN2 <- lm(R80P ~ Nitro_000_015, data = total_val)#
# lm_R80PN5 <- lm(R80P ~ Nitro_000_030, data = total_val)
# AIC(lm_R80PN1, lm_R80PN2,lm_R80PN5)
# lm_R80PN1 <- lm(R80P ~ CEC_000_005, data = total_val)
# lm_R80PN2 <- lm(R80P ~ CEC_000_015, data = total_val)#
# lm_R80PN5 <- lm(R80P ~ CEC_000_030, data = total_val)
# AIC(lm_R80PN1, lm_R80PN2,lm_R80PN5)
# lm_R80PN1 <- lm(R80P ~ SOC_000_005, data = total_val)
# lm_R80PN2 <- lm(R80P ~ SOC_000_015, data = total_val)
# lm_R80PN5 <- lm(R80P ~ SOC_000_030, data = total_val)#
# AIC(lm_R80PN1, lm_R80PN2,lm_R80PN5)
# Select the most optimal population kernel size
lm_pop1 <- lm(R80P ~ pop500, data = total_val)
lm_pop2 <- lm(R80P ~ pop1000, data = total_val)#
lm_pop3 <- lm(R80P ~ pop5000, data = total_val)
lm_pop4 <- lm(R80P ~ pop10000, data = total_val)
AIC(lm_pop1, lm_pop2, lm_pop3,lm_pop4)

# Select the most optimal roads dataset
# lm_road1 <- lm(R80P ~ distRoads, data = total_val)#
# lm_road2 <- lm(R80P ~ distSelRoads, data = total_val)
# AIC(lm_road1, lm_road2)

# generate a linear model without any spatial correlation structure and including impact
dat_sel <- total_val
lm_R80Ptot <- lm(R80P ~ TCmean500 +  Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030 +  Pseas + CWD + MAP + impact + Vpre + pop1000 + distRoads , data =dat_sel)
# lm_R80P <- step(lm_R80Ptot, direction = 'backward')# backward selection of relevant variables
lms_R80P <- arm::standardize(lm_R80Ptot)# scale coef of covariates to enhance comparison
summary(lms_R80P)# 
plot(lms_R80P)# check the model fit 
plot(dat_sel$R80P,fitted(lms_R80P))
abline(0,1, col = 'red')
library(faraway)
vif(lms_R80P)# vif greater than 5 is considered problematic

# generate a linear model without any spatial correlation structure without including impact
lm_R80Ptot2 <- lm(R80P ~ TCmean500 +  Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030 +  Pseas + CWD + MAP + pop1000 + distRoads, data =dat_sel)
# lm_R80P2 <- step(lm_R80Ptot2, direction = 'backward')# backward selection of relevant variables
lms_R80P2 <- arm::standardize(lm_R80Ptot2)# scale coef of covariates to enhance comparison
summary(lms_R80P2)# 
plot(lms_R80P2)# check the model fit 
plot(dat_sel$R80P,fitted(lms_R80P2))
abline(0,1, col = 'red')
library(faraway)
vif(lms_R80P2)# vif greater than 5 is considered problematic

library(adegenet)
library(spdep)

# check if the residuals have a significant spatial correlation structure
xy <- t(as.matrix(rbind(total_val$lon,total_val$lat)))#matrix(runif(100),ncol=2)
yourcn <- chooseCN(xy, type = 6, result.type = "listw")# 3 neighbors
# yourcn <- chooseCN(xy, type = 7, a = 1, dmin = 0.0001, result.type = "listw")
mortst <- lm.morantest(lms_R80P, yourcn, alternative="two.sided")
mortst2 <- lm.morantest(lms_R80P2, yourcn, alternative="two.sided")

# run lagrange multiplier test to know which spatial model suits the data
lagtst <- lm.LMtests(lms_R80P, yourcn, test = c("LMerr","LMlag","RLMerr","RLMlag"))#lag
lagtst2 <- lm.LMtests(lms_R80P2, yourcn, test = c("LMerr","LMlag","RLMerr","RLMlag"))#lag
library(sf)
dat_scale <- cbind(dat_sel[,c(1:8)],as.data.frame(scale(dat_sel[,-c(1,2,3,4,5,6,7,8)])))# scale the data to enable comparing the coefs (subtract mean and divide by sd)
dat_scale_sf = st_as_sf(dat_scale, coords = c("lon", "lat"), crs = 4326)
library(spatialreg)

# linear model without spatial correlation structure - full model
fit_1_lm <- lm(R80P ~ TCmean500 +  Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030 +  Pseas + CWD + MAP + impact + Vpre + pop1000 + distRoads, data =dat_scale)
summary(fit_1_lm)

plot(fit_1_lm)# check the model fit 
par(mfrow = c(2, 2), oma = c(0, 0, 2, 0))
plot(fit_1_lm, which = 1:4)

png(file.path(ifolder, 'LM_diag_R80p.png'), width = 1400, height = 1100)
par(mfrow = c(2, 2), oma = c(0,5, 3, 0),mar=c(5,6,4,2) + 0.1)
plot(fit_1_lm, id.n = 5, labels.id = NULL, cex.axis = 3, cex.lab =3)  # 5 id numbers non-lin | normal distr | variance | outliers
dev.off()

png(file.path(ifolder, 'LM_fit_R80p.png'), width = 1400, height = 1100)
sqplot(dat_sel$R80P,fitted(fit_1_lm),xlab = 'R80P', ylab = 'Fitted', cex = 2, cex.axis = 3, cex.lab =3)# true vs fitted
dev.off()


# spatial simultaneous autoregressive lag model  - full model
fit_2_lag <- lagsarlm(R80P ~ TCmean500 +  Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030 +  Pseas + CWD + MAP + impact + Vpre + pop1000 + distRoads , data = dat_scale_sf, yourcn)
summary(fit_2_lag)

impacts(fit_2_lag, listw=yourcn)

# patial simultaneous autoregressive error model - full model
fit_3_err <- errorsarlm(R80P ~ TCmean500 +  Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030 +  Pseas + CWD + MAP + impact + Vpre + pop1000 + distRoads, data = dat_scale_sf, yourcn)
summary(fit_3_err)

# ------------------------------------------------------------------
# linear model without spatial correlation structure - part model
fit_1_lm_part <- lm(R80P ~ TCmean500 +  Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030 +  Pseas + CWD + MAP + pop1000 + distRoads, data =dat_scale)
summary(fit_1_lm_part)

plot(fit_1_lm_part)# check the model fit 
par(mfrow = c(2, 2), oma = c(0, 0, 2, 0))
plot(fit_1_lm_part, which = 1:4)

png(file.path(ifolder, 'LM_diag_R80p_part.png'), width = 1400, height = 1100)
par(mfrow = c(2, 2), oma = c(0,5, 3, 0),mar=c(5,6,4,2) + 0.1)
plot(fit_1_lm_part, id.n = 5, labels.id = NULL, cex.axis = 3, cex.lab =3)  # 5 id numbers non-lin | normal distr | variance | outliers
dev.off()

png(file.path(ifolder, 'LM_fit_R80p_part.png'), width = 1400, height = 1100)
sqplot(dat_sel$R80P,fitted(fit_1_lm_part),xlab = 'R80P', ylab = 'Fitted', cex = 2, cex.axis = 3, cex.lab =3)# true vs fitted
dev.off()


# spatial simultaneous autoregressive lag model  - full model
fit_2_lag_part <- lagsarlm(R80P ~ TCmean500 +  Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030 +  Pseas + CWD + MAP + pop1000 + distRoads , data = dat_scale_sf, yourcn)
summary(fit_2_lag_part)

impacts(fit_2_lag_part, listw=yourcn)

# patial simultaneous autoregressive error model - full model
fit_3_err_part <- errorsarlm(R80P ~ TCmean500 +  Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030 +  Pseas + CWD + MAP + pop1000 + distRoads, data = dat_scale_sf, yourcn)
summary(fit_3_err_part)
```

```{r YrYr}
lm_YrYrTC1 <- lm(YrYr ~ TCmean500, data = total_val)
lm_YrYrTC2 <- lm(YrYr ~ TCmean1000, data = total_val)
lm_YrYrTC3 <- lm(YrYr ~ TCmean5000, data = total_val)#
AIC(lm_YrYrTC1, lm_YrYrTC2, lm_YrYrTC3)

# Select the most optimal soil depth
# lm_YrYrN1 <- lm(YrYr ~ Nitro_000_005, data = total_val)
# lm_YrYrN2 <- lm(YrYr ~ Nitro_000_015, data = total_val)
# lm_YrYrN5 <- lm(YrYr ~ Nitro_000_030, data = total_val)#
# AIC(lm_YrYrN1, lm_YrYrN2, lm_YrYrN5)
# lm_YrYrN1 <- lm(YrYr ~ CEC_000_005, data = total_val)#
# lm_YrYrN2 <- lm(YrYr ~ CEC_000_015, data = total_val)
# lm_YrYrN5 <- lm(YrYr ~ CEC_000_030, data = total_val)
# AIC(lm_YrYrN1, lm_YrYrN2, lm_YrYrN5)
# lm_YrYrN1 <- lm(YrYr ~ SOC_000_005, data = total_val)
# lm_YrYrN2 <- lm(YrYr ~ SOC_000_015, data = total_val)#
# lm_YrYrN5 <- lm(YrYr ~ SOC_000_030, data = total_val)
# AIC(lm_YrYrN1, lm_YrYrN2, lm_YrYrN5)
# Select the most optimal population kernel size
lm_YrYrpop1 <- lm(YrYr ~ pop500, data = total_val)
lm_YrYrpop2 <- lm(YrYr ~ pop1000, data = total_val)
lm_YrYrpop3 <- lm(YrYr ~ pop5000, data = total_val)
lm_YrYrpop4 <- lm(YrYr ~ pop10000, data = total_val)#
AIC(lm_YrYrpop1, lm_YrYrpop2, lm_YrYrpop3,lm_YrYrpop4)

# Select the most optimal roads dataset
# lm_YrYrroad1 <- lm(YrYr ~ distRoads, data = total_val)
# lm_YrYrroad2 <- lm(YrYr ~ distSelRoads, data = total_val)
# AIC(lm_YrYrroad1, lm_YrYrroad2)

# generate a linear model without any spatial correlation structure
dat_sel <- total_val
lm_YrYrtot <- lm(YrYr ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP +  impact + Vpre +pop10000 + distRoads , data = dat_sel)
# lm_YrYr <- step(lm_YrYrtot, direction = 'backward')# backward selection of relevant variables
lms_YrYr <- arm::standardize(lm_YrYrtot)# scale coef of covariates to enhance comparison
summary(lms_YrYr)# 
plot(lms_YrYr)# check the model fit 
plot(dat_sel$YrYr,fitted(lms_YrYr))
abline(0,1, col = 'red')
# total_val$resR80P1 <- residuals(lms_R80P)
# total_val$fitR80P1 <- fitted(lms_R80P)
library(faraway)
vif(lms_YrYr)# vif greater than 5 is considered problematic

lm_YrYrtot2 <- lm(YrYr ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP + pop10000 + distRoads , data = dat_sel)
# lm_YrYr <- step(lm_YrYrtot, direction = 'backward')# backward selection of relevant variables
lms_YrYr2 <- arm::standardize(lm_YrYrtot2)# scale coef of covariates to enhance comparison
summary(lms_YrYr2)# 

library(adegenet)
library(spdep)

# check if the residuals have a significant spatial correlation structure
xy <- t(as.matrix(rbind(total_val$lon,total_val$lat)))#matrix(runif(100),ncol=2)
yourcn <- chooseCN(xy, type = 6, result.type = "listw")# 3 neighbors
# yourcn <- chooseCN(xy, type = 7, a = 1, dmin = 0.0001, result.type = "listw")
mortst <- lm.morantest(lms_YrYr, yourcn, alternative="two.sided")
mortst2 <- lm.morantest(lms_YrYr2, yourcn, alternative="two.sided")

# run lagrange multiplier test to know which spatial model suits the data
lagtst <- lm.LMtests(lms_YrYr, yourcn, test = c("LMerr","LMlag","RLMerr","RLMlag"))#,"error"
lagtst2 <- lm.LMtests(lms_YrYr2, yourcn, test = c("LMerr","LMlag","RLMerr","RLMlag"))#,"lag"
library(sf)
dat_scale <- cbind(dat_sel[,c(1:8)],as.data.frame(scale(dat_sel[,-c(1,2,3,4,5,6,7,8)])))# scale the data to enable comparing the coefs
dat_scale_sf = st_as_sf(dat_scale, coords = c("lon", "lat"), crs = 4326)
library(spatialreg)

# linear model without spatial correlation structure
fit_YrYr_1_lm <- lm(YrYr ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP +  impact + Vpre +pop10000 + distRoads  , data =dat_scale)
summary(fit_YrYr_1_lm)

plot(fit_YrYr_1_lm)# check the model fit 
par(mfrow = c(2, 2), oma = c(0, 0, 2, 0))
plot(fit_YrYr_1_lm, which = 1:4)

png(file.path(ifolder, 'LM_diag_YrYr.png'), width = 1400, height = 1100)
par(mfrow = c(2, 2), oma = c(0,5, 3, 0),mar=c(5,6,4,2) + 0.1)
plot(fit_YrYr_1_lm, id.n = 5, labels.id = NULL, cex.axis = 3, cex.lab =3)  # 5 id numbers non-lin | normal distr | variance | outliers
dev.off()

png(file.path(ifolder, 'LM_fit_YrYr.png'), width = 1400, height = 1100)
sqplot(dat_sel$YrYr,fitted(fit_YrYr_1_lm),xlab = 'YrYr', ylab = 'Fitted', cex = 2, cex.axis = 3, cex.lab =3)# true vs fitted
dev.off()


# spatial simultaneous autoregressive lag model 
fit_YrYr_2_lag <- lagsarlm(YrYr ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP +  impact + Vpre +pop10000 + distRoads , data = dat_scale_sf, yourcn)
summary(fit_YrYr_2_lag)

impacts(fit_YrYr_2_lag, listw=yourcn)

# patial simultaneous autoregressive error model
fit_YrYr_3_err <- errorsarlm(YrYr ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP +  impact + Vpre +pop10000 + distRoads, data = dat_scale_sf, yourcn)
summary(fit_YrYr_3_err)

#-----------------------------------------------------
# linear model without spatial correlation structure
fit_YrYr_1_lm_part <- lm(YrYr ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP +  pop10000 + distRoads  , data =dat_scale)
summary(fit_YrYr_1_lm_part)

plot(fit_YrYr_1_lm_part)# check the model fit 
par(mfrow = c(2, 2), oma = c(0, 0, 2, 0))
plot(fit_YrYr_1_lm_part, which = 1:4)

png(file.path(ifolder, 'LM_diag_YrYr_part.png'), width = 1400, height = 1100)
par(mfrow = c(2, 2), oma = c(0,5, 3, 0),mar=c(5,6,4,2) + 0.1)
plot(fit_YrYr_1_lm_part, id.n = 5, labels.id = NULL, cex.axis = 3, cex.lab =3)  # 5 id numbers non-lin | normal distr | variance | outliers
dev.off()

png(file.path(ifolder, 'LM_fit_YrYr_part.png'), width = 1400, height = 1100)
sqplot(dat_sel$YrYr,fitted(fit_YrYr_1_lm_part),xlab = 'YrYr', ylab = 'Fitted', cex = 2, cex.axis = 3, cex.lab =3)# true vs fitted
dev.off()


# spatial simultaneous autoregressive lag model 
fit_YrYr_2_lag_part <- lagsarlm(YrYr ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP + pop10000 + distRoads , data = dat_scale_sf, yourcn)
summary(fit_YrYr_2_lag_part)

impacts(fit_YrYr_2_lag_part, listw=yourcn)

# patial simultaneous autoregressive error model
fit_YrYr_3_err_part <- errorsarlm(YrYr ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP  +pop10000 + distRoads, data = dat_scale_sf, yourcn)
summary(fit_YrYr_3_err_part)
```

```{r RRI}
lm_RRITC1 <- lm(RRI ~ TCmean500, data = total_val)
lm_RRITC2 <- lm(RRI ~ TCmean1000, data = total_val)
lm_RRITC3 <- lm(RRI ~ TCmean5000, data = total_val)#
AIC(lm_RRITC1, lm_RRITC2, lm_RRITC3)

lm_RRIpop1 <- lm(RRI ~ pop500, data = total_val)
lm_RRIpop2 <- lm(RRI ~ pop1000, data = total_val)
lm_RRIpop3 <- lm(RRI ~ pop5000, data = total_val)
lm_RRIpop4 <- lm(RRI ~ pop10000, data = total_val)#
AIC(lm_RRIpop1, lm_RRIpop2, lm_RRIpop3,lm_RRIpop4)

lm_RRItot <- lm(RRI ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP +  impact + Vpre +pop10000 + distRoads , data =dat_sel)
# lm_RRI <- step(lm_RRItot, direction = 'backward')# backward selection of relevant variables
lms_RRI <- arm::standardize(lm_RRItot)# scale coef of covariates to enhance comparison
summary(lms_RRI)# 
plot(lms_RRI)# check the model fit 
plot(dat_sel$RRI,fitted(lms_RRI))
abline(0,1, col = 'red')
library(faraway)
vif(lms_RRI)# vif greater than 5 is considered problematic

lm_RRItot2 <- lm(RRI ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP +  pop10000 + distRoads , data =dat_sel)
# lm_RRI <- step(lm_RRItot, direction = 'backward')# backward selection of relevant variables
lms_RRI2 <- arm::standardize(lm_RRItot2)# scale coef of covariates to enhance comparison
summary(lms_RRI2)# 
plot(lms_RRI2)# check the model fit 
plot(dat_sel$RRI,fitted(lms_RRI2))
abline(0,1, col = 'red')
library(faraway)
vif(lms_RRI2)# vif greater than 5 is considered problematic

library(adegenet)
library(spdep)

# check if the residuals have a significant spatial correlation structure
xy <- t(as.matrix(rbind(total_val$lon,total_val$lat)))#matrix(runif(100),ncol=2)
yourcn <- chooseCN(xy, type = 6, result.type = "listw")# 3 neighbors
# yourcn <- chooseCN(xy, type = 7, a = 1, dmin = 0.0001, result.type = "listw")
mortst <- lm.morantest(lms_RRI, yourcn, alternative="two.sided")
mortst2 <- lm.morantest(lms_RRI2, yourcn, alternative="two.sided")

# run lagrange multiplier test to know which spatial model suits the data
lagtst <- lm.LMtests(lms_RRI, yourcn, test = c("LMerr","LMlag","RLMerr","RLMlag"))#,"SARMA"
lagtst2 <- lm.LMtests(lms_RRI2, yourcn, test = c("LMerr","LMlag","RLMerr","RLMlag"))#,"SARMA"
library(sf)
dat_scale <- cbind(dat_sel[,c(1:8)],as.data.frame(scale(dat_sel[,-c(1,2,3,4,5,6,7,8)])))# scale the data to enable comparing the coefs
dat_scale_sf = st_as_sf(dat_scale, coords = c("lon", "lat"), crs = 4326)
library(spatialreg)

# linear model without spatial correlation structure
fit_RRI_1_lm <- lm(RRI ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP +  impact + Vpre + pop10000 + distRoads, data =dat_scale)
summary(fit_RRI_1_lm)

plot(fit_RRI_1_lm)# check the model fit 
par(mfrow = c(2, 2), oma = c(0, 0, 2, 0))
plot(fit_RRI_1_lm, which = 1:4)

png(file.path(ifolder, 'LM_diag_R80p.png'), width = 1400, height = 1100)
par(mfrow = c(2, 2), oma = c(0,5, 3, 0),mar=c(5,6,4,2) + 0.1)
plot(fit_1_lm, id.n = 5, labels.id = NULL, cex.axis = 3, cex.lab =3)  # 5 id numbers non-lin | normal distr | variance | outliers
dev.off()

png(file.path(ifolder, 'LM_fit_R80p.png'), width = 1400, height = 1100)
sqplot(dat_sel$R80P,fitted(fit_1_lm),xlab = 'R80P', ylab = 'Fitted', cex = 2, cex.axis = 3, cex.lab =3)# true vs fitted
dev.off()


# spatial simultaneous autoregressive lag model 
fit_RRI_2_lag <- lagsarlm(RRI ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP +  impact + Vpre + pop10000 + distRoads, data = dat_scale_sf, yourcn)
summary(fit_YrYr_2_lag)

impacts(fit_2_lag, listw=yourcn)

# patial simultaneous autoregressive error model
fit_RRI_3_err <- errorsarlm(RRI ~TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP +  impact + Vpre + pop10000 + distRoads, data = dat_scale_sf, yourcn)
summary(fit_RRI_3_err)

# --------------------------------------------------
# --------------------------------------------------
# linear model without spatial correlation structure
fit_RRI_1_lm_part <- lm(RRI ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP +  pop10000 + distRoads, data =dat_scale)
summary(fit_RRI_1_lm_part)

plot(fit_RRI_1_lm_part)# check the model fit 
par(mfrow = c(2, 2), oma = c(0, 0, 2, 0))
plot(fit_RRI_1_lm_part, which = 1:4)

png(file.path(ifolder, 'LM_diag_R80p.png'), width = 1400, height = 1100)
par(mfrow = c(2, 2), oma = c(0,5, 3, 0),mar=c(5,6,4,2) + 0.1)
plot(fit_RRI_1_lm_part, id.n = 5, labels.id = NULL, cex.axis = 3, cex.lab =3)  # 5 id numbers non-lin | normal distr | variance | outliers
dev.off()

png(file.path(ifolder, 'LM_fit_R80p.png'), width = 1400, height = 1100)
sqplot(dat_sel$R80P,fitted(fit_RRI_1_lm_part),xlab = 'R80P', ylab = 'Fitted', cex = 2, cex.axis = 3, cex.lab =3)# true vs fitted
dev.off()


# spatial simultaneous autoregressive lag model 
fit_YrYr_2_lag_part <- lagsarlm(RRI ~ TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP +  pop10000 + distRoads, data = dat_scale_sf, yourcn)
summary(fit_YrYr_2_lag_part)

impacts(fit_YrYr_2_lag_part, listw=yourcn)

# patial simultaneous autoregressive error model
fit_RRI_3_err_part <- errorsarlm(RRI ~TCmean5000 + Elev + Slope  + Nitro_000_030  + CEC_000_030  + SOC_000_030   +  Pseas + CWD + MAP + pop10000 + distRoads, data = dat_scale_sf, yourcn)
summary(fit_RRI_3_err_part)

```
